# -*- coding: utf-8 -*-
"""Time ideal

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KH0aoyaVahRY4tidfG3QI85u9akf60M0
"""

import random

#Listando os clubes que estão na serie A
clubes = ["Flamengo", "Palmeiras", "Atlético Mineiro", "Fortaleza", "Corinthians", "Internacional", "São Paulo", "Athletico Paranaense", "Cuiabá", "Bahia", "Fluminense", "Juventude", "Botafogo", "Cruzeiro", "Vasco", "Grêmio", "Criciuma", "Atlético Goianiense", "Vitoria", "Bragantino"]


# Dicionário com os elencos de cada time (NUNCA MAIS FAÇO ISSO)
elencos = {
    "Flamengo": ["Rossi","Leo Pereira","Fabricio Bruno","Ayrton Lucas","Varella","Erick Pulgar","De la Cruz","Arrascaeta","Bruno Henrique","Everton Cebolinha","Pedro"],
    "Palmeiras": ["Weverton", "Murilo", "Gustavo Gómez", "Piquerez", "Marcos Rocha", "Richard Rios", "Anibal Moreno", "Raphael Veiga", "Endrick", "Estevão", "Flaco Lopez"],
    "Atlético Mineiro": ["Everson", "Jemerson", "Battaglia", "Guilherme Arana", "Rubens", "Franco", "Otavio", "Zaracho", "Scarpa", "Paulinho", "Hulk"],
    "Fortaleza": ["Felipe Alves", "Daniel Guedes", "Titi", "Jussa", "Carlinhos", "Éderson", "Felipe", "Lucas Crispim", "Robson", "Matheus Vargas", "Wellington Paulista"],
    "Corinthians": ["Cássio", "Torres", "De menezes", "Hugo", "Fagner", "Bidon", "Ranielle", "Garro", "Angel Romero", "Wesley", "Yuri Alberto"],
    "Internacional": ["Rochet", "Mercado", "Vitão", "Renê", "Bustos", "Bruno Henrique", "Thiago Maia", "Mauricio", "Wanderson", "Wesley", "Rafael Borré"],
    "São Paulo": ["Rafael", "Allan Franco", "Arboleda", "Patryck", "Igor Vinicius", "Bobadilla", "Alisson", "Rodtigo Nestor", "Ferreirinha", "Luciano", "Calleri"],
    "Athletico Paranaense": ["Bento", "Kaique Rocha", "Thiago Heleno", "Godoy", "Esquivel", "Fernandinho", "Cuello", "Julimar", "Erick", "Canobbio", "Manstriani"],
    "Cuiabá": ["Mateus Passinato", "Marllon", "Bruno Alves", "Mateus Alexandre", "Riquelme", "Lucas Mineiro", "Fernando Sobral", "Denilson", "Cafu", "Darick", "Pitta"],
    "Bahia": ["Marcos Felipe", "Cuesta", "Kanu", "Luciano Juba", "Arias", "Caio Alexandre", "Jean Lucas", "Thaciano", "Cauly", "Everton Ribeiro", "Everaldo"],
    "Fluminense": ["Fabio", "Felipe Melo", "Manoel", "Marcelo", "Samuel Xavier", "Lima", "Martinelli", "Ganso", "Arias", "Douglas Costa", "Cano"],
    "Juventude": ["Gabriel", "Danilo", "Ze Marcos", "João Lucas", "Gabriel Inocencio", "Jadson", "Jean Carlos", "Lucas Barbosa", "Nenê", "Caique Gonçalves", "Erick"],
    "Botafogo": ["Jhon", "Lucas Halter", "Bastos", "Hugo", "Ponte", "Danilo Fernandes", "Marlon Freitas", "Savarino", "Jeffinho", "Junior Santos", "Tiquinho Soares"],
    "Cruzeiro": ["Anderson", "Ivaldo", "Neris", "William", "Marllon", "Ramiro", "Romero", "Matteus Fernades", "Arthur Gomes", "Lucas Silva", "Rafa Silva"],
    "Vasco": ["Leo Jardim", "Medel", "Leo Pelé", "Paulo Henrique", "Lucas Piton", "Sforza", "Mateus Carvalho", "Payet", "Rossi", "David", "Vegetti"],
    "Grêmio": ["Marchesin", "Pedro Geromel", "Kanneman", "Fabio", "Cuiabano", "Villasanti", "Dodi", "Cristaldo", "Soteldo", "Pavon", "João Pedro"],
    "Criciuma": ["Gustavo", "Angel", "Rodrigo", "Marcelo Henrique", "Claudinho", "Gustavo Barreto", "Felipe Mateus", "Higor Meritão", "Marquinhos Gabriel", "Bolasie", "Arthur"],
    "Atlético Goianiense": ["Ronaldo Strada", "Alix", "Adriano Martins", "Guilherme R.", "Bruno Tubarão", "Shaylon", "Roni", "Gomes", "Maguinho", "Luiz Fernando", "Rodriguez"],
    "Vitoria": ["Lucas Willians", "Bruno Uvini", "Wagner Leonardo", "Lucas Estavão", "Zeca", "Willian Oliveira", "Luan", "Mateusinho", "Osvaldo", "Mateus Gonçalves", "Alerrandro"],
    "Bragantino": ["Cleiton", "Eduardo Santos", "Luan Candido", "Juninho Capixaba", "Pedro Henrique", "Ramires", "Gustavinho", "Natahan Mendes", "Victor Naum", "Mosqueira", "Eduardo Sacha"],
    }

def escolher_time():
    clube1, clube2 = random.sample(clubes, 2)
    print("Monte o seu time ideal com os jogadores do Brasileirão 2024")
    print("="*30)
    print("TIME 1 =", clube1)
    for i, jogador in enumerate(elencos[clube1]):
        print(f"{i+1}. {jogador}")
    print("="*30)
    print("TIME 2 =", clube2)
    for i, jogador in enumerate(elencos[clube2]):
        print(f"{i+12}. {jogador}")

    time = []
    while len(time) < 11:
        escolha = int(input(f"Escolha o jogador {len(time)+1}: "))
        if escolha >= 1 and escolha <= 11:
            jogador_escolhido = elencos[clube1][escolha-1]
        elif escolha >= 12 and escolha <= 22:
            jogador_escolhido = elencos[clube2][escolha-12]
        else:
            print("Escolha inválida. Escolha um número entre 1 e 22.")
            continue

        if jogador_escolhido not in time:
            time.append(jogador_escolhido)
        else:
            print("Este jogador já foi selecionado. Escolha outro.")

    print("\nParabéns! Você montou o seguinte time dos sonhos:")
    for i, jogador in enumerate(time):
        print(f"{i+1}. {jogador}")

# Chamada da função principal
escolher_time()